const driver = {
  name: 'TCI Professionale Casambi',
  shortName: 'TCI Prof',
  artNo: 'PRO-CASAMBI',
  settings: [
    {
      name: '300mA',
      current: 300,
      minVoltage: 10,
      maxVoltage: 54,
      maxPower: 16,
    },
    {
      name: '350mA',
      current: 350,
      minVoltage: 10,
      maxVoltage: 54,
      maxPower: 18.5,
    },
    {
      name: '400mA',
      current: 400,
      minVoltage: 10,
      maxVoltage: 54,
      maxPower: 21.5,
    },
    {
      name: '450mA',
      current: 450,
      minVoltage: 10,
      maxVoltage: 54,
      maxPower: 24,
    },
    {
      name: '500mA',
      current: 500,
      minVoltage: 10,
      maxVoltage: 54,
      maxPower: 27,
    },
    {
      name: '550mA',
      current: 550,
      minVoltage: 10,
      maxVoltage: 54,
      maxPower: 29.5,
    },
    {
      name: '600mA',
      current: 600,
      minVoltage: 10,
      maxVoltage: 54,
      maxPower: 32,
    },
    {
      name: '650mA',
      current: 650,
      minVoltage: 10,
      maxVoltage: 54,
      maxPower: 35,
    },
    {
      name: '700mA',
      current: 700,
      minVoltage: 10,
      maxVoltage: 51,
      maxPower: 36,
    },
    {
      name: '750mA',
      current: 750,
      minVoltage: 10,
      maxVoltage: 50,
      maxPower: 38,
    },
    {
      name: '800mA',
      current: 800,
      minVoltage: 10,
      maxVoltage: 47,
      maxPower: 38,
    },
    {
      name: '850mA',
      current: 850,
      minVoltage: 10,
      maxVoltage: 44,
      maxPower: 38,
    },
    {
      name: '900mA',
      current: 900,
      minVoltage: 10,
      maxVoltage: 42,
      maxPower: 38,
    },
    {
      name: '950mA',
      current: 950,
      minVoltage: 10,
      maxVoltage: 40,
      maxPower: 38,
    },
    {
      name: '1000mA',
      current: 1000,
      minVoltage: 10,
      maxVoltage: 38,
      maxPower: 38,
    },
    {
      name: '1050mA',
      current: 1050,
      minVoltage: 10,
      maxVoltage: 36,
      maxPower: 38,
    },
  ]
}

export default driver
